/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login_22;

import java.sql.Connection;
import Miscelanea.Miscelanea;

import static Bd.ConectaBD.conectaBD;
import java.awt.Color;
import java.awt.Container;
import java.awt.Event;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import java.util.EventObject;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author Ruben
 */
public class Login extends JDialog {

   JDialog ventana;
   private Connection conexion;

    public Login(Frame owner, boolean modal) {
        super(owner, true);
   
        initComponents();
        // Añadir propiedades a los elementos gráficos......
        jT_servidor.setName("Servidor de la Bd");
        jT_servidor.putClientProperty("etiqueta", jL_servidor);
        jT_servidor.putClientProperty("RegExp", "[A-Za-z0-9]{3,}");
        jT_servidor.putClientProperty("MsgRegExp", "nombre de la máquina o ip");
        jL_servidor.setVisible(false);
        
        jT_nombreBD.setName("Nombre de la Bd");
        jT_nombreBD.putClientProperty("etiqueta", jL_nombreBd);
        jT_nombreBD.putClientProperty("RegExp", "[A-Za-z0-9]{3,}");
        jT_nombreBD.putClientProperty("MsgRegExp", " Letras y/o numeros min 3 car");
        jL_nombreBd.setVisible(false);
        
        // Añadir propiedades a los elementos gráficos......
        jT_usuario.setName("Usuario");
        jT_usuario.putClientProperty("etiqueta", jL_usuario);
        jT_usuario.putClientProperty("RegExp", "[A-Za-z0-9]{2,}");
        jT_usuario.putClientProperty("MsgRegExp", "Empieza Mays, min 3 alfanumericos");
               
        //jL_usuario.setVisible(false);
        
        jT_contraseña.putClientProperty("etiqueta", jL_contraseña);
        jT_contraseña.putClientProperty("RegExp", "(?=.*[a-z])(?!.*[A-Z])\\w{4,}$");
        //jT_contraseña.putClientProperty("RegExp", "(?=.*[a-z])(?=.*\\d)(?!.*[A-Z])\\w{4,}$");
        jT_contraseña.putClientProperty("MsgRegExp", "Empieza Mays, min 5 cars, contiene minus y numeros");
       // jL_contraseña.setVisible(false);
        
        jC_tipoBD.setName("tipo de Bd");
        //jC_tipoBD.getDocument().putProperty("etiqueta", jL_tipoBD);
        jC_tipoBD.putClientProperty("etiqueta", jL_tipoBD);
        jL_tipoBD.setVisible(true);
        
        ventana = this;
        
        jB_Conectar.setEnabled(false);
        
        jB_Conectar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
               System.out.println("Se ejecuto el actionPerformed manual..");
            }
        });
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jT_usuario = new javax.swing.JTextField();
        jT_contraseña = new javax.swing.JTextField();
        jC_tipoBD = new javax.swing.JComboBox<>();
        jT_nombreBD = new javax.swing.JTextField();
        jT_servidor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jB_Conectar = new javax.swing.JButton();
        jL_usuario = new javax.swing.JLabel();
        jL_contraseña = new javax.swing.JLabel();
        jL_tipoBD = new javax.swing.JLabel();
        jL_nombreBd = new javax.swing.JLabel();
        jL_servidor = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 51));
        jLabel1.setText("Usuario:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 51));
        jLabel2.setText("Contraseña:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Tipo BD:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Nombre BD:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Servidor:");

        jT_usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jT_usuarioKeyReleased(evt);
            }
        });

        jT_contraseña.setName("Contraseña"); // NOI18N
        jT_contraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jT_contraseñaKeyReleased(evt);
            }
        });

        jC_tipoBD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona Tipo de BD", "MySql", "Oracle" }));
        jC_tipoBD.setBorder(null);
        jC_tipoBD.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jC_tipoBD.setName("Tipo de BD"); // NOI18N
        jC_tipoBD.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jC_tipoBDItemStateChanged(evt);
            }
        });
        jC_tipoBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jC_tipoBDActionPerformed(evt);
            }
        });

        jT_nombreBD.setText("prog");
        jT_nombreBD.setName("Nombre de la BD"); // NOI18N
        jT_nombreBD.setOpaque(false);
        jT_nombreBD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jT_nombreBDFocusLost(evt);
            }
        });
        jT_nombreBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_nombreBDActionPerformed(evt);
            }
        });

        jT_servidor.setText("localhost");
        jT_servidor.setName("Servidor de la BD"); // NOI18N
        jT_servidor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jT_servidorFocusLost(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 255));
        jLabel7.setText("Datos de Conexion");

        jB_Conectar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jB_Conectar.setForeground(new java.awt.Color(255, 0, 0));
        jB_Conectar.setText("< < Conectar > >");
        jB_Conectar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jB_ConectarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jB_ConectarMouseExited(evt);
            }
        });
        jB_Conectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_ConectarActionPerformed(evt);
            }
        });

        jL_usuario.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jL_usuario.setForeground(new java.awt.Color(204, 0, 0));
        jL_usuario.setText("* usuario Obligatorio");

        jL_contraseña.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jL_contraseña.setForeground(new java.awt.Color(204, 0, 0));
        jL_contraseña.setText("*Contraseña obligatoria");
        jL_contraseña.setToolTipText("");

        jL_tipoBD.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jL_tipoBD.setForeground(new java.awt.Color(204, 0, 0));
        jL_tipoBD.setText("*Tipo Bd obligatorio");
        jL_tipoBD.setToolTipText("");
        jL_tipoBD.setName("jL_tipoBD"); // NOI18N

        jL_nombreBd.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jL_nombreBd.setForeground(new java.awt.Color(204, 0, 0));
        jL_nombreBd.setText("*Tipo Bd obligatorio");
        jL_nombreBd.setToolTipText("");
        jL_nombreBd.setName("jL_tipoBD"); // NOI18N

        jL_servidor.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jL_servidor.setForeground(new java.awt.Color(204, 0, 0));
        jL_servidor.setText("*Tipo Bd obligatorio");
        jL_servidor.setToolTipText("");
        jL_servidor.setName("jL_tipoBD"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jB_Conectar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(3, 3, 3)
                                            .addComponent(jLabel2))
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jL_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jT_usuario)
                                    .addComponent(jT_contraseña)
                                    .addComponent(jC_tipoBD, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jT_nombreBD)
                                    .addComponent(jT_servidor, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jL_contraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jL_tipoBD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jL_nombreBd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jL_servidor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel7)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jT_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jL_usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jT_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jL_contraseña))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jC_tipoBD))
                .addGap(2, 2, 2)
                .addComponent(jL_tipoBD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jT_nombreBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jL_nombreBd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jT_servidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jL_servidor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jB_Conectar)
                .addGap(20, 20, 20))
        );

        jL_usuario.getAccessibleContext().setAccessibleName("etiquetaNombre");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jB_ConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_ConectarActionPerformed
       
        if( compruebaDatos(this.getContentPane())){
            conexion=conectaBD((String)jC_tipoBD.getSelectedItem(),jT_servidor.getText(),"3306",
                                    jT_nombreBD.getText(),jT_usuario.getText(),jT_contraseña.getText());
            
            if(conexion!=null){
                JOptionPane.showMessageDialog(this, "Conexión Correcta", 
                                                "Login", JOptionPane.INFORMATION_MESSAGE);
                ventana.setVisible(false);
            }
            else{
                 int opc=JOptionPane.showConfirmDialog(null, "Error de conexión, Quieres reintentar?", 
                                                    "Login", JOptionPane.YES_NO_OPTION);
                 
                 if(opc==JOptionPane.NO_OPTION){
                     JOptionPane.showMessageDialog(this, "Adios...", 
                                                "Saliendo de la  Aplicacion", JOptionPane.INFORMATION_MESSAGE);
                     System.exit(0);
                 }
                 
            }
        }
        
        
    }//GEN-LAST:event_jB_ConectarActionPerformed

    private void jT_nombreBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_nombreBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_nombreBDActionPerformed

    private void jC_tipoBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jC_tipoBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jC_tipoBDActionPerformed

    private void jB_ConectarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_ConectarMouseEntered
        jB_Conectar.setBackground(Color.GRAY);
    }//GEN-LAST:event_jB_ConectarMouseEntered

    private void jB_ConectarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_ConectarMouseExited
        jB_Conectar.setBackground(Color.lightGray);
    }//GEN-LAST:event_jB_ConectarMouseExited

    private void jC_tipoBDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jC_tipoBDItemStateChanged

     if(evt.getStateChange()== ItemEvent.SELECTED){  
         
        JComboBox lista = (JComboBox)evt.getSource();
        JLabel     etiqueta =(JLabel)lista.getClientProperty("etiqueta");

        if( lista.getSelectedIndex()==0){
               etiqueta.setVisible(true);  
        }
        else{
               etiqueta.setVisible(false);  
        }
     }
    }//GEN-LAST:event_jC_tipoBDItemStateChanged

    private void jT_usuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_usuarioKeyReleased
     compruebajT(evt);
    }//GEN-LAST:event_jT_usuarioKeyReleased

    private void jT_contraseñaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_contraseñaKeyReleased
       compruebajT(evt);
    }//GEN-LAST:event_jT_contraseñaKeyReleased

    private void jT_nombreBDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_nombreBDFocusLost
        compruebajT(evt);
    }//GEN-LAST:event_jT_nombreBDFocusLost

    private void jT_servidorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_servidorFocusLost
         compruebajT(evt);
    }//GEN-LAST:event_jT_servidorFocusLost
    //------------------------------------------------
    private void compruebajT(EventObject evt){
    /*  if(evt instanceof KeyEvent)
          evt=(KeyEvent)evt;*/
       
      JTextField campo    =(JTextField)evt.getSource();  
      JLabel     etiqueta =(JLabel) campo.getClientProperty("etiqueta");
      
      if( !campo.getText().trim().isEmpty()){// comprobar formato
          
               if( !campo.getText().matches((String)campo.getClientProperty("RegExp")) ){
                     etiqueta.setText("Formato incorrecto!!"+(String)campo.getClientProperty("MsgRegExp"));
                     etiqueta.setVisible(true);
                     campo.setToolTipText((String)campo.getClientProperty("MsgRegExp"));
                     
                     jB_Conectar.setEnabled(false);
                  } 
                else  {
                       etiqueta.setVisible(false);
                       //Comprobar habilitar el boton conectar...
                       if(!compruebaTodosValidos())
                          jB_Conectar.setEnabled(true);
               }
       
      }
      else{
          etiqueta.setText((String)campo.getClientProperty("MsgRegExp"));
          etiqueta.setVisible(true);
          jB_Conectar.setEnabled(false);
      }
        
    }   
//---------------------------------------------------------
     boolean compruebaTodosValidos(){
        return jL_contraseña.isVisible() ||
               jL_nombreBd.isVisible()  ||
               jL_servidor.isVisible()  ||
               jL_tipoBD.isVisible()  ||
               jL_usuario.isVisible(); 
      
    }
//---------------------------------------------------------    
    private boolean  compruebaDatos(Container panel){
       
        boolean error=true;
        panel.getComponent(1);
        for (int i = 0; i < panel.getComponentCount(); i++) {
         JComponent c        =   (JComponent)panel.getComponent(i);
         
           if(c instanceof JTextField){
               if( ((JTextField) c).getText().trim().isEmpty()){
                   JLabel     etiqueta =(JLabel) ((JTextField) c).getDocument().getProperty("etiqueta");
               
                  /* JOptionPane.showMessageDialog(this, 
                           ((JTextField) c).getName()+ " es obligatorio!",
                              "Datos incorrectos", JOptionPane.ERROR_MESSAGE);
                   ((JTextField) c).requestFocus();*/
                   etiqueta.setVisible(true);
                   error= false;
            }
               
           }
           else
               if(c instanceof JComboBox ){
                   if( ((JComboBox) c).getSelectedIndex() ==0){
                   /*  JOptionPane.showMessageDialog(this, 
                           "Debes seleccionar un "+((JComboBox) c).getName()+ " válido!",
                           "Datos incorrectos", JOptionPane.ERROR_MESSAGE);*/
                    JLabel     etiqueta =(JLabel)jC_tipoBD.getClientProperty("etiqueta");
                    etiqueta.setVisible(true);
                    
                   ((JComboBox) c).requestFocus();
                    error= false; 
                   }
                 
                }
         
        }
       
        return error;
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Conectar;
    private javax.swing.JComboBox<String> jC_tipoBD;
    private javax.swing.JLabel jL_contraseña;
    private javax.swing.JLabel jL_nombreBd;
    private javax.swing.JLabel jL_servidor;
    private javax.swing.JLabel jL_tipoBD;
    private javax.swing.JLabel jL_usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jT_contraseña;
    private javax.swing.JTextField jT_nombreBD;
    private javax.swing.JTextField jT_servidor;
    private javax.swing.JTextField jT_usuario;
    // End of variables declaration//GEN-END:variables

    public Connection getConexion() {
        return conexion;
    }

    public void setConexion(Connection conexion) {
        this.conexion = conexion;
    }
}
